name: Caller for MegaLinter

on: 
  workflow_dispatch:

  # Pull Requests to main
  pull_request:
    branches: [master, main]

env: 
   branch_name: v2  

  
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  megalinter:
    uses: rartych/xCAMARA/.github/workflows/megalinter.yml@main
    # with:
    #   ref: v2