name: Execute MegaLinter linting using configuration from branch indicated by input 
description: 'A reusable action for linting using configuration from branch indicated by input `ref` variable '

on:
  # For a workflow to be reusable, the values for on must include workflow_call
  workflow_call:
    inputs:
      ref:
        description: 'The branch, tag, or commit to check out'
        type: string
        required: false
        default: 'main'

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
        # If you use VALIDATE_ALL_CODEBASE = true, you can remove this line to
        # improve performance
        # fetch-depth: 0
          
    - name: Checkout linting config
      uses: actions/checkout@v4
      with:
        repository: rartych/xCAMARA
        ref: ${{ inputs.ref }}
        sparse-checkout: |
          # config/linting/lint_function
          # config/linting/.spectral.yml
          config/linting/
        sparse-checkout-cone-mode: false  

    - name: Copy specified folder to workspace root
      run: |
        cp -RTv ${{ github.workspace }}/config/linting ${{ github.workspace }}

    - name: Display directory contents
      run: tree -a
    - name: Display lint_function
      run: ls ${{ github.workspace }}/lint_function  -la
      
