name: Sparse Checkout Example

on:
  # For a workflow to be reusable, the values for on must include workflow_call
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: rartych/xCAMARA
        ref: main
        sparse-checkout: |
          # config/linting/lint_function
          # config/linting/.spectral.yml
          config/linting/
        sparse-checkout-cone-mode: false  

    - name: Copy specified folder to workspace root
      run: |
        cp -Rv ${{ github.workspace }}/config/linting/ ${{ github.workspace }}

    - name: Display directory contents
      run: tree -a
    - name: Display lint_function
      run: ls ${{ github.workspace }}/lint_function  -la
      
